### ISSUE TITLE
CRAN

### ISSUE THREAD

**Issue by gdkrmr** [ropenscilabs/umapr#23]
Are you planing to put this on CRAN?

**Comment by seaaan** [comment]
Thanks for your interest. We are not planning to put umapr on CRAN because of other UMAP-related developments in the R world. 

* The [umap](https://cran.r-project.org/web/packages/umap/index.html) package is now on CRAN. It provides R/Rcpp implementation of UMAP as well as the same interface to the Python version that umapr provides. 

* The [uwot](https://github.com/jlmelville/uwot) package provides a second R/Rcpp implementation of UMAP. 

Thanks again for your interest.
